In [2]:
import pandas as pd
file_path = '/Users/shigeyuki-t/Desktop/FirstExperiment/分析用/05.csv'
dataset = pd.read_csv(file_path)
dataset.head(3)

,Unnamed: 0,sensor_id,data_time,QuestionNum,choice_left,choice_right,event,isAnswerCorrect,response_time,response_time_ave,...,scroll_count,scroll_length,scroll_speed,scroll_time,tap_count,tap_interval,tap_position_x,tap_position_y,taskNum,view_position
0,0,suke.kazuma@gmail.com,2024-05-07 03:33:51,0,0,0,scroll,True,0.0,0.0,...,2,0.0,0.0,0.5,0,0.0,0.0,0.0,1,513.0
1,1,suke.kazuma@gmail.com,2024-05-07 03:33:50,0,0,0,scroll,True,0.0,0.0,...,1,935.0,9350.0,0.1,0,0.0,0.0,0.0,1,513.0
2,2,suke.kazuma@gmail.com,2024-05-07 03:33:55,0,1,0,response,True,0.0,0.0,...,2,0.0,0.0,0.5,1,0.0,0.0,0.0,1,513.0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17872 entries, 0 to 17871
Data columns (total 22 columns):
Unnamed: 0           17872 non-null int64
sensor_id            17872 non-null object
data_time            17872 non-null object
QuestionNum          17872 non-null int64
choice_left          17872 non-null int64
choice_right         17872 non-null int64
event                17872 non-null object
isAnswerCorrect      17872 non-null bool
response_time        17872 non-null float64
response_time_ave    17872 non-null float64
screen_height        17872 non-null int64
screen_width         17872 non-null int64
scroll_count         17872 non-null int64
scroll_length        17872 non-null float64
scroll_speed         17872 non-null float64
scroll_time          17872 non-null float64
tap_count            17872 non-null int64
tap_interval         17872 non-null float64
tap_position_x       17872 non-null float64
tap_position_y       17872 non-null float64
taskNum              17872 non-null int64
view_position        17872 non-null float64
dtypes: bool(1), float64(9), int64(9), object(3)
memory usage: 2.9+ MB

In [4]:
dataset.describe()

,Unnamed: 0,QuestionNum,choice_left,choice_right,response_time,response_time_ave,screen_height,screen_width,scroll_count,scroll_length,scroll_speed,scroll_time,tap_count,tap_interval,tap_position_x,tap_position_y,taskNum,view_position
count,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000,17872.000000
mean,8935.500000,77.161929,33.562892,31.261470,6.052865,11.362357,835.017122,392.941137,145.515947,305.285813,221.803827,4.667329,66.378973,5.644231,135.621505,191.429124,65.502238,29910.213153
std,5159.346341,44.273359,23.761142,21.657783,20.016043,8.647612,101.921501,18.623963,105.075389,1461.489288,2732.775480,10.639696,44.879529,18.626745,153.908233,213.912419,44.065405,19852.965286
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,600.000000,320.000000,1.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,4467.750000,40.000000,13.000000,12.000000,0.400000,7.367380,812.000000,375.000000,60.000000,23.666667,16.289386,0.900000,27.000000,0.400000,0.000000,0.000000,27.000000,12606.916667
50%,8935.500000,78.000000,30.000000,28.000000,2.200000,10.573256,844.000000,390.000000,127.000000,241.500000,58.333333,2.300000,61.000000,2.100000,36.333328,27.000000,60.000000,28231.250000
75%,13403.250000,117.000000,52.000000,49.000000,6.400000,12.513131,852.000000,414.000000,211.000000,388.000000,141.190476,5.500000,103.000000,6.200000,308.000000,417.500000,102.000000,46588.000000
max,17871.000000,151.000000,114.000000,89.000000,886.400000,114.666667,1194.000000,430.000000,484.000000,63917.666667,242237.500000,873.500000,159.000000,886.700000,531.500000,657.333328,151.000000,89287.500000

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns
print(dataset['isAnswerCorrect'].value_counts())
predict_param = dataset['isAnswerCorrect']

True     9153
False    8719
Name: isAnswerCorrect, dtype: int64